// CONN-2 — GitHub PR (PRD §18). Deterministic exporter via the `gh` CLI: a fresh repo (or a
// given existing one), an empty `main` to diff against, the generated tree committed onto
// its own branch, pushed, and PR'd. No model call. Gated behind SEC-1 like every connector —
// this module only runs once gate.js has confirmed an approved Inbox item for this write.
//
// Operates ENTIRELY inside `generatedDir` (git-init's THAT directory, never the daemon's own
// repo) — "nothing writes to the user's real repo" (PRD non-negotiable) applies to connector
// writes exactly as it does to agent CLI spawning (SEC-2).
//
// `opts.exec` is injectable so this can be unit tested without ever touching a real GitHub
// account (see github.selftest.mjs) — default is a real `git`/`gh` spawn.
import { spawn } from 'node:child_process';
import { writeFile } from 'node:fs/promises';
import path from 'node:path';

function defaultExec(cmd, args, cwd) {
  return new Promise((resolve, reject) => {
    const p = spawn(cmd, args, { cwd, shell: true });
    let stdout = '';
    let stderr = '';
    p.stdout.on('data', (d) => (stdout += d));
    p.stderr.on('data', (d) => (stderr += d));
    p.on('error', reject);
    p.on('exit', (code) => {
      if (code === 0) return resolve({ stdout: stdout.trim(), stderr: stderr.trim() });
      reject(Object.assign(new Error(`${cmd} ${args.join(' ')} exited with ${code}: ${stderr.trim()}`), { stdout, stderr }));
    });
  });
}

function slugify(s) {
  return String(s)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80);
}

/**
 * @param {string} generatedDir - absolute path to the run's generated backend (caller-owned)
 * @param {object} contract - the validated architecture contract
 * @param {{runId?: string, repoName?: string, remoteUrl?: string, base?: string, exec?: Function}} [opts]
 */
export async function exportGithubPR(generatedDir, contract, opts = {}) {
  const exec = opts.exec ?? defaultExec;
  const run = (cmd, args) => exec(cmd, args, generatedDir);

  const base = opts.base ?? 'main';
  const branch = opts.branch ?? `pact/${slugify(opts.runId ?? contract.meta.id)}`;
  const title = opts.title ?? `PACT: ${contract.meta.id}`;
  const body =
    opts.body ??
    [
      `Generated by PACT from contract \`${contract.meta.id}\`.`,
      '',
      `- ${(contract.features ?? []).length} features`,
      `- ${(contract.apis ?? []).length} APIs`,
      `- ${(contract.collections ?? []).length} collections`,
    ].join('\n');

  const isRepo = await run('git', ['rev-parse', '--is-inside-work-tree']).then(
    () => true,
    () => false,
  );

  if (!isRepo) {
    // `generatedDir` is very likely the SAME directory the live preview booted from
    // (runner.js's node_modules + .pact-deps-hash marker live there) — never commit those.
    await writeFile(path.join(generatedDir, '.gitignore'), 'node_modules/\n.pact-deps-hash\n', 'utf8');
    await run('git', ['init']);
    await run('git', ['checkout', '-B', base]);
    // An empty commit on `base` gives the PR something real to diff against — a repo whose
    // only commit IS the generated backend has no meaningful base to compare to.
    await run('git', ['commit', '--allow-empty', '-m', 'Initial commit']);

    const repoName = opts.repoName ?? `pact-generated-${slugify(opts.runId ?? contract.meta.id)}`;
    if (opts.remoteUrl) {
      await run('git', ['remote', 'add', 'origin', opts.remoteUrl]);
      await run('git', ['push', '-u', 'origin', base]);
    } else {
      await run('gh', ['repo', 'create', repoName, '--private', '--source=.', '--remote=origin', '--push']);
    }
  }

  await run('git', ['checkout', '-B', branch]);
  await run('git', ['add', '-A']);
  await run('git', ['commit', '-m', title]);
  await run('git', ['push', '-u', 'origin', branch]);

  const pr = await run('gh', ['pr', 'create', '--title', title, '--body', body, '--base', base, '--head', branch]);
  return { connector: 'github', branch, base, prUrl: pr.stdout };
}
